name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary_target: x86_64-unknown-linux-musl
            artifact_name: sonar-as-code
            asset_name: sonar-as-code-linux-amd64
          - os: windows-latest
            binary_target: x86_64-pc-windows-msvc
            artifact_name: sonar-as-code.exe
            asset_name: sonar-as-code-windows-amd64.exe
          - os: macos-latest
            binary_target: x86_64-apple-darwin
            artifact_name: sonar-as-code
            asset_name: sonar-as-code-macos-amd64
    steps:
      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install musl-tools
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install rust windows msvc target
        if: matrix.os == 'windows-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-msvc
          profile: minimal
          override: true
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
